# scrutinizer-ci.com configuration
imports:
    - javascript
    - php
filter:
    excluded_paths: [libraries/php-gettext/*, libraries/bfShapeFiles/*, PMAStandard/*, js/jquery/*, js/jqplot/*, js/openlayers/*, js/codemirror/*, js/canvg/*, js/tracekit/*, js/sprintf.js, test/libraries/php-gettext/*]
tools:
    php_code_sniffer:
        config:
            standard: "PMAStandard"
