services:
  error_report:
    class: '\PhpMyAdmin\ErrorReport'
    arguments: ['@http_request', '@relation', '@template']

  export:
    class: '\PhpMyAdmin\Export'
    arguments: ['@dbi']

  http_request:
    class: '\PhpMyAdmin\Utils\HttpRequest'

  import:
    class: '\PhpMyAdmin\Import'

  navigation:
    class: '\PhpMyAdmin\Navigation\Navigation'
    arguments: ['@template', '@relation', '@dbi']

  normalization:
    class: '\PhpMyAdmin\Normalization'
    arguments: ['@dbi']

  relation:
    class: '\PhpMyAdmin\Relation'
    arguments: ['@dbi', '@template']

  status_data:
    class: '\PhpMyAdmin\Server\Status\Data'

  template:
    class: 'PhpMyAdmin\Template'

  transformations:
    class: 'PhpMyAdmin\Transformations'
